### ISSUE TITLE
Test linear regression

### ISSUE THREAD

**Issue by Ishikawa7** [Ishikawa7/SemeionTechCollabTest#4]
**Test linear regression on Iris dataset (using scikit-learn)**

**Comment by Ishikawa7** [comment]
OPS logistic regression

**Comment by LostInGitHubLand** [comment]
Mission complete (prima bozza)

**Comment by Ishikawa7** [comment]
@LostInGitHubLand ho visto che hai pubblicato la regressione logistica sul branch _LogisticRegression_, se non ci sono altre cose che devi fare su quello puoi procedere ad una pull request :)

**Comment by LostInGitHubLand** [comment]
Ok, quindi i passi sono

1) crea un branch ed etichettalo con ciò che hai fatto (da visual studio)
2) fai una Pull Request (da Github)
3) rispondi all'issue (da Github)


Ps attendo un attimo a fare la pull reuest perchè lo sto sistemando un po'.

Buon week end

Il Sab 2 Dic 2023, 15:09 Davide Grimaldi ***@***.***> ha
scritto:
